services:
  onlyoffice-server:
    image: onlyoffice/documentserver
    container_name: onlyoffice-server
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    networks:
      - proxy
      - onlyoffice
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.onlyoffice.entrypoints=http"
      - "traefik.http.routers.onlyoffice.rule=Host(`${ONLYOFFICE_DOMAIN}`)"
      - "traefik.http.routers.onlyoffice-secure.tls=true"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      - "traefik.http.routers.onlyoffice-secure.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.onlyoffice-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice-https-redirect"
      - "traefik.http.routers.onlyoffice-secure.entrypoints=https"
      - "traefik.http.routers.onlyoffice-secure.rule=Host(`${ONLYOFFICE_DOMAIN}`)"
      - "traefik.http.routers.onlyoffice-secure.service=onlyoffice"
      - "traefik.http.routers.onlyoffice-secure.middlewares=onlyoffice-header"
      - "traefik.http.middlewares.onlyoffice-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.onlyoffice-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.onlyoffice-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.onlyoffice-header.headers.stsPreload=true"
      - "traefik.http.middlewares.onlyoffice-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.onlyoffice-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.onlyoffice-header.headers.customRequestHeaders.X-Forwarded-Proto=https"
    environment:
      - "JWT_SECRET=${JWT_SECRET}"
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - ONLYOFFICE_HTTPS_HSTS_ENABLED=false
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice
      - onlyoffice_cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - onlyoffice_example-files:/var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts
      
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
      - onlyoffice
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:12
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    networks:
      - onlyoffice
    expose:
      - '5432'
    volumes:
      - onlyoffice_postgresql_data:/var/lib/postgresql

networks:
  onlyoffice:
    driver: bridge
  proxy:
    external: true

volumes:
  onlyoffice_postgresql_data:
  onlyoffice_data:
  onlyoffice_log:
  onlyoffice_cache:
  onlyoffice_example-files: