http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`pve.example.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    adguard:
      entryPoints:
        - "https"
      rule: "Host(`adguard.example.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: adguard
    homeassitant:
      entryPoints:
        - "https"
      rule: "Host(`homeassistant.example.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: homeassitant
  
#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1:8006"
        passHostHeader: true
    adguard:
      loadBalancer:
        servers:
          - url: "https://192.168.1.2"
        passHostHeader: true
    homeassitant:
      loadBalancer:
        servers:
          - url: "https://1192.168.1.3:8123"
        passHostHeader: true
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
        - default-headers