---
- name: Setup K3S Masters
  hosts: k3s_agents
  become: true

  tasks:
    - name: apt update
      ansible.builtin.include_tasks:
        file: ./tasks/apt-update.yaml
    - name: install k3s
      ansible.builtin.include_tasks:
        file: ./tasks/agents/k3s-install.yaml