---
- name: "Uninstall K3S on agent nodes"
  hosts: k3s_agents
  become: true

  tasks:
    - name: "run uninstaller"
      ansible.builtin.shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true