apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-staging
  namespace: kubernetes-dashboard
spec:
  secretName: cert-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.yoursite.com"
  dnsNames:
    - "local.yoursite.com"
    - "*.local.yoursite.com"